version: "3"

services:

  db:
    image: postgres:12.0-alpine
    ports:
      - 5434
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api_news

  app:
    container_name: app
    build: .
    command: sh -c "alembic upgrade head && uvicorn server:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=api_news
      - DB_HOST=db
      - REDIS=redis://redis:6379/0
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db


  redis:
    container_name: redis
    image: redis:6.2-alpine


  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  celery-worker:
    container_name: worker
    build: .
    command: celery worker -B -l info -Q fetch_queue --loglevel=info
    volumes:
      - .:/app
    environment:
      - REDIS=redis://redis:6379/0
    depends_on:
      - app
      - redis

  celery-consumer:
    container_name: celery_cons
    build: .
    command: celery -A tasks.tasks.client worker -l info
    volumes:
      - .:/app
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=api_news
      - DB_HOST=db
      - REDIS=redis://redis:6379/0
    depends_on:
      - app
      - redis
      - db

