"""init

Revision ID: af243044ecf3
Revises: 
Create Date: 2023-03-06 22:43:19.395111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af243044ecf3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parse_date', sa.Date(), nullable=False),
    sa.Column('publication_date', sa.Integer(), nullable=True),
    sa.Column('header', sa.String(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('page_link', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_news_id'), 'news', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_news_publication_date'), 'news', ['publication_date'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_news_publication_date'), table_name='news', schema='public')
    op.drop_index(op.f('ix_public_news_id'), table_name='news', schema='public')
    op.drop_table('news', schema='public')
    # ### end Alembic commands ###
